site_name: TigerGraphX

nav:
  - Home:
      - "Welcome": index.md
      - "Introduction to TigerGraphX": introduction.md
      - "GraphRAG Overview": graphrag/graphrag_overview.md
  - Getting Started:
      - Installation: getting_started/installation.md
      - "TigerGraphX Quick Start":
        - "Using TigerGraph as Graph Database": getting_started/quick_start_graph.ipynb
        - "Using TigerGraph as Vector Database": getting_started/quick_start_vector.ipynb
        - "Using TigerGraph for Graph and Vector Database": getting_started/quick_start_both.ipynb
  - GraphRAG:
      - "GraphRAG Overview": graphrag/graphrag_overview.md
      - "Supporting LightRAG": graphrag/lightrag.ipynb
      - "Supporting Microsoft's GraphRAG":
          - "Part 1 - Setup and Data Preparation": graphrag/msft_graphrag_1.md
          - "Part 2 - Graph Creation and Data Loading": graphrag/msft_graphrag_2.ipynb
          - "Part 3 - Graph Analysis": graphrag/msft_graphrag_3.ipynb
          - "Part 4 - Hybrid Retrieval and Integration with LLM": graphrag/msft_graphrag_4.ipynb
  - API Reference:
      - Introduction: reference/introduction.md
      - Core:
          - Graph: reference/01_core/graph.md
          - NodeView: reference/01_core/nodeview.md
      - Vector Search:
          - Vector DB: reference/02_vector_search/vector_db.md
          - Embedding: reference/02_vector_search/embedding.md
          - Search Engine: reference/02_vector_search/search_engine.md
      - LLM:
          - LMM Manager: reference/03_llm/llm_manager.md
          - Chat: reference/03_llm/chat.md
      - Config:
          - BaseConfig: reference/04_config/base_config.md
          - Graph DB:
              - TigerGraphConnectionConfig: reference/04_config/01_graph_db/tigergraph_connection_config.md
              - Schema Configuration: reference/04_config/01_graph_db/schema_config.md
              - Loading Job Configuration: reference/04_config/01_graph_db/loading_job_config.md
          - Query:
              - Node Specification: reference/04_config/02_query/node_spec.md
              - Neighbor Specification: reference/04_config/02_query/neighbor_spec.md
          - Settings:
              - Vector DB Settings: reference/04_config/03_settings/vector_db_settings.md
              - LLM Settings: reference/04_config/03_settings/llm_settings.md
              - Embedding Settings: reference/04_config/03_settings/embedding_settings.md
              - Chat Settings: reference/04_config/03_settings/chat_settings.md
              - Settings: reference/04_config/03_settings/settings.md
      - Graphrag:
          - BaseContextBuilder: reference/05_graphrag/base_context_builder.md
      - Pipelines:
          - Parquet Processor: reference/06_pipelines/parquet_processor.md
      - Utils:
          - RetryMixin: reference/07_utils/retry_mixin.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - content.code.copy
    - content.code.select
  language: en
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/auto-mode
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            # General
            show_source: false
            # Headings
            heading_level: 3
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            # Members
            members_order: source
            inherited_members: false
            # Headings
            docstring_section_style: list
            # Signatures
            show_signature: true

markdown_extensions:
  # Styled blocks for notes, warnings, tips, and other types of content
  - admonition 
  - pymdownx.details:
  # Emoji
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Code block highlight
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid # Diagrams
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # Tabs
  - pymdownx.tabbed:
      alternate_style: true
